### ISSUE TITLE
Handler crashed with error reflect: call of reflect.Value.Int on string Value

### ISSUE THREAD

**Issue by JulioRamos0** [adamwalach/openvpn-web-ui#26]
How can I solve this error?
Environment
Platform: Raspberry Pi 3 B +
OS: linux
Architecture: arm
The source was compiled on the Raspberry Pi.

Action: Update the configuration of the  `default` profile
Initially I had to comment on that configuration in the code because it gave me the same error.
Log

```
[ORM]2019/09/27 15:15:01  -[Queries/default] - [  OK / db.QueryRow /     0.2ms] - [SELECT `id`, `profile`, `port`, `proto`, `ca`, `cert`, `key`, `cipher`, `keysize`, `auth`, `dh`, `server`, `ifconfig_pool_persist`, `keepalive`, `max_clients`, `management` FROM `o_v_config` WHERE `profile` = ? ] - `default`
2019/09/27 15:15:01 [D] [utils.go:49] {
,
	"Profile": "default",
	"Port": 0,
	"Proto": "",
	"Ca": "",
	"Cert": "",
	"Key": "",
	"Cipher": "",
	"Keysize": 0,
	"Auth": "",
	"Dh": "",
	"Server": "",
	"IfconfigPoolPersist": "",
	"Keepalive": "",
	"MaxClients": 0,
	"Management": ""
} 
2019/09/27 15:15:01 [C] [panic.go:679] the request url is  /ov/config
2019/09/27 15:15:01 [C] [panic.go:679] Handler crashed with error reflect: call of reflect.Value.Int on string Value
2019/09/27 15:15:01 [C] [panic.go:679] /usr/local/go/src/runtime/panic.go:679
2019/09/27 15:15:01 [C] [panic.go:679] /usr/local/go/src/reflect/value.go:986
2019/09/27 15:15:01 [C] [panic.go:679] /go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/db.go:214
2019/09/27 15:15:01 [C] [panic.go:679] /go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/db.go:92
2019/09/27 15:15:01 [C] [panic.go:679] /go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/db.go:617
2019/09/27 15:15:01 [C] [panic.go:679] /go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/orm.go:239
2019/09/27 15:15:01 [C] [panic.go:679] /go/src/github.com/adamwalach/openvpn-web-ui/controllers/ovconfig.go:61
2019/09/27 15:15:01 [C] [panic.go:679] /go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/router.go:787
2019/09/27 15:15:01 [C] [panic.go:679] /usr/local/go/src/net/http/server.go:2802
2019/09/27 15:15:01 [C] [panic.go:679] /usr/local/go/src/net/http/server.go:1890
2019/09/27 15:15:01 [C] [panic.go:679] /usr/local/go/src/runtime/asm_arm.s:868
```

**Comment by d3vilh** [comment]
have kind the same issue on **RPI 4b**:
```
ebat@netm:~/tempo $ cat /etc/debian_version
10.10
ebat@netm:~/tempo $ uname -a
Linux netm 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
```
Managed to build everything for arm v71, but it can't run properly.
DB seems on the place, instances and users were created, but it throws following, when I run it:
```
2021/10/01 12:12:56 [D] [models.go:88] {1 default openvpn:2080 tcp /etc/openvpn/ 127.0.0.1 2021-10-01 09:26:49.944566004 +0000 UTC 2021-10-01 09:26:49.944570911 +0000 UTC}
[ORM]2021/10/01 12:12:56  -[Queries/default] - [  OK / db.QueryRow /     0.1ms] - [SELECT `id`, `profile`, `port`, `proto`, `ca`, `cert`, `key`, `cipher`, `keysize`, `auth`, `dh`, `server`, `ifconfig_pool_persist`, `keepalive`, `max_clients`, `management` FROM `o_v_config` WHERE `profile` = ? ] - `default`
panic: reflect: call of reflect.Value.Int on string Value

goroutine 1 [running]:
reflect.Value.Int(...)
	/usr/local/go/src/reflect/value.go:1334
```

**Update:**
**As a WA** you can disable default profile configuration submit to `o_v_config` table by commenting out `createDefaultOVConfig()` function as part of `init()` in `models.go`:

```
func init() {
	initDB()
	createDefaultUsers()
	createDefaultSettings()
//	createDefaultOVConfig()
}
```
This will skip createDefaultOVConfig and web server starts normally.

**Comment by d3vilh** [comment]
Here is the full log:
```
ebat@netm:~/openvpn-web-ui-armv71-build $ docker run -v /home/pi/openvpn:/etc/openvpn -v /home/pi/openvpn/db:/opt/openvpn-gui/db -e REQ_COUNTRY='UA' -e REQ_CITY='Chayka' -e REQ_OU='Fuck off' -e REQ_CN='MyOpenVPN' -e REQ_PROVINCE='Kyiv' -e REQ_ORG='Copyleft Certificate Co' -e KEY_NAME='EBANAT' -p 8080:8080/tcp --privileged local/openvpn-ui
+ set -e
+ export OVDIR=/etc/openvpn
+ OVDIR=/etc/openvpn
+ cd /opt/
+ '[' '!' -f /etc/openvpn/.provisioned ']'
+ cd /opt/openvpn-gui
+ mkdir -p db
+ ./openvpn-web-ui
table `user` already exists, skip
table `settings` already exists, skip
table `o_v_config` already exists, skip
[ORM]2021/10/01 11:09:04  -[Queries/default] - [  OK / db.QueryRow /     0.1ms] - [SELECT `id`, `login`, `name`, `email`, `password`, `lastlogintime`, `created`, `updated` FROM `user` WHERE `name` = ? ] - `Administrator`
2021/10/01 11:09:04 [D] [models.go:67] {1 admin Administrator root@localhost $s2$16384$8$1$LbvssW/rd8CnSJleeYk6Nybp$rzgKocfD2AhU0fTG/Se3kJhmvf0esR8apL9i3L1Cz7w=  0001-01-01 00:00:00 +0000 UTC 2021-10-01 11:08:00.362380973 +0000 UTC 2021-10-01 11:08:00.362388621 +0000 UTC}
[ORM]2021/10/01 11:09:04  -[Queries/default] - [  OK / db.QueryRow /     0.1ms] - [SELECT `id`, `profile`, `m_i_address`, `m_i_network`, `o_v_config_path`, `server_address`, `created`, `updated` FROM `settings` WHERE `profile` = ? ] - `default`
2021/10/01 11:09:04 [D] [models.go:88] {1 default openvpn:2080 tcp /etc/openvpn/ 127.0.0.1 2021-10-01 11:08:00.378308761 +0000 UTC 2021-10-01 11:08:00.378315613 +0000 UTC}
[ORM]2021/10/01 11:09:04  -[Queries/default] - [  OK / db.QueryRow /     0.1ms] - [SELECT `id`, `profile`, `port`, `proto`, `ca`, `cert`, `key`, `cipher`, `keysize`, `auth`, `dh`, `server`, `ifconfig_pool_persist`, `keepalive`, `max_clients`, `management` FROM `o_v_config` WHERE `profile` = ? ] - `default`
panic: reflect: call of reflect.Value.Int on string Value

goroutine 1 [running]:
reflect.Value.Int(...)
	/usr/local/go/src/reflect/value.go:1334
github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm.(*dbBase).collectFieldValue(0x109fa48, 0x10b6820, 0x10ef5f0, {0x576528, 0x113a310, 0x199}, 0x1, 0x8fb5c0)
	/go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/db.go:214 +0x1708
github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm.(*dbBase).collectValues(0x109fa48, 0x10b6820, {0x576528, 0x113a310, 0x199}, {0x10ae300, 0x10, 0x10}, 0x0, 0x1, ...)
	/go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/db.go:92 +0x1a0
github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm.(*dbBase).Insert(0x109fa48, {0x66bcdc, 0x100c060}, 0x10b6820, {0x576528, 0x113a310, 0x199}, 0x8fb5c0)
	/go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/db.go:376 +0xb8
github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm.(*orm).Insert(0x100e190, {0x57e640, 0x113a310})
	/go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/orm.go:166 +0x98
github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm.(*orm).ReadOrCreate(0x100e190, {0x57e640, 0x113a310}, {0x5b41c7, 0x7}, {0x0, 0x0, 0x0})
	/go/src/github.com/adamwalach/openvpn-web-ui/vendor/github.com/astaxie/beego/orm/orm.go:149 +0x36c
github.com/adamwalach/openvpn-web-ui/models.createDefaultOVConfig()
	/go/src/github.com/adamwalach/openvpn-web-ui/models/models.go:116 +0x7c
github.com/adamwalach/openvpn-web-ui/models.init.0()
	/go/src/github.com/adamwalach/openvpn-web-ui/models/models.go:18 +0x20
ebat@netm:~/openvpn-web-ui-docker-build $
```
